### ISSUE TITLE
craftingComplete event

### ISSUE THREAD

**Issue by zm3y** [DoctorMcKay/node-tf2#10]
Hello, It's me again. I try make simple crafter. Craft work fine, but when items crafted, craftingComplete should be emitted, but it don't. I just got three 23 messages (it's destroy event), one 21 message (its create) and 1 undefined message from gc. I think it 1003 but it's undefined, why?

**Comment by DoctorMcKay** [comment]
Similar bug in node-steam, PR sent in seishun/node-steam#215
