### ISSUE TITLE
Readme mismatch

### ISSUE THREAD

**Issue by dragonbanshee** [DoctorMcKay/node-tf2#11]
The delete function is defined in the readme as `delete`, but defined in the file as `deleteItem`. One of them needs to be renamed since it caused "undefined is not a function" errors.

**Comment by DoctorMcKay** [comment]
Looks fine to me?

https://github.com/DoctorMcKay/node-tf2#deleteitemitem
https://github.com/DoctorMcKay/node-tf2/blob/master/index.js#L216

**Comment by dragonbanshee** [comment]
Hmm, maybe I was looking at something else, but I swear it said `delete(item)`, and that's also what I had in my code from a long time ago. Oh well.
