### ISSUE TITLE
SteamGC.on("message" == 4009

### ISSUE THREAD

**Issue by Mediumwater** [DoctorMcKay/node-tf2#13]
Hello, i found out that k_EMsgGCServerGoodbye = 4009, but how to react to that? 
I mean, should i close the connection and try again or what do that mean? 
Can you pls help me?

**Comment by DoctorMcKay** [comment]
Are you using this module? If so, [it's already being handled](https://github.com/DoctorMcKay/node-tf2/blob/master/handlers.js#L35).

**Comment by Mediumwater** [comment]
actually i just found out directly after posting this, that the Problem occurs with require("steamid"); and then with the SteamGC.on("message", listener out of that package. When i searched the Internet i found your Project at first with the code 4009 mentioned. I decided to let the Issue stay to maybe get a usefull idea how to solve it. 

Acutally i think i already found a solution, with just resending my request. Time will tell if its a good solution. Or even if the message 4009 accoures in the normal system behavior, maybe it was just because of the test scenario, which got sometimes executed.

thx for the fast answer 👍
