### ISSUE TITLE
Inventory not updated after crafting untill bot is off

### ISSUE THREAD

**Issue by devossa** [DoctorMcKay/node-tf2#15]
my bot crafts Class Tokens,
for some reason it craft as many tokens as i tell it to but its backpack doesn't update even in the browser untill i turn it off
here's my code:
```javascript
getOwnInv((inv) => {
    let itemsDict = createDictionary(keepCraftWeps(inv));
    let checked = checkForTokens(itemsDict, tokenClass, amount);
    if (!checked.success) {
        clientUser.chatMessage(steamID, checked.message);
    } else {
        clientUser.chatMessage(steamID, "Crafting " + amount + " " + tokenName + " ....");
        for (var i = 0; i < amount; i++) {
            console.log(itemsDict[tokenClass].slice(3 * i, 3 * (i + 1)));
            tf2.craft(itemsDict[tokenClass].slice(3 * i, 3 * (i + 1)));
        }
    }
    return;
});
```
where:
amount is number of tokens to craft,
tokenClass is like "Pyro" or "Spy",
 itemsDict is an Object of arrays of weapons ids grouped by Class,
inv is inventory Object from steam-tradeoffer-manager,
other functions do what their names say

**Comment by DoctorMcKay** [comment]
That's normal. Inventories you pull from steam community are cached, and only update if:

- A trade offer is accepted exchanging an item from the game
- A real-time trade session is started
- You start playing the game
- You stop playing the game

If you want the up-to-date backpack info, you have to get it from node-tf2.

**Comment by devossa** [comment]
oh i see, thanks for the help
