### ISSUE TITLE
Why inventoty not update after craft item?

### ISSUE THREAD

**Issue by haskell-md2** [DoctorMcKay/node-tf2#24]
When I create an item, the changes are not shown in the inventory, however, after the bot is turned off, the inventory is updated. 

What should I do to fix it?

**Comment by DoctorMcKay** [comment]
Because Steam inventories are cached. The only way to invalidate the cache and force it to update is one of the following:

- Start TF2
- Stop TF2
- Start a real-time trade session (**not** a trade offer)
- Complete a trade involving a TF2 item

**Comment by haskell-md2** [comment]
> Because Steam inventories are cached. The only way to invalidate the cache and force it to update is one of the following:
> 
> * Start TF2
> * Stop TF2
> * Start a real-time trade session (**not** a trade offer)
> * Complete a trade involving a TF2 item

Благодарю. But I have one more question. How i must stop TF? Use client.logOff()?

**Comment by DoctorMcKay** [comment]
Use `client.gamesPlayed([])` to report that you've stopped playing a game.

**Comment by danthonywalker** [comment]
Sorry to revive an old issue, but don't you also receive items when you get the "You have new items!" pop-up in game and you view and dismiss it? Is that functionality available in this library?
