### ISSUE TITLE
itemSchema fails to load on restart

### ISSUE THREAD

**Issue by blindinglt** [DoctorMcKay/node-tf2#4]
I've noticed that if I close out then restart the connection to GC, the itemSchema won't load unless significant time has passed since the last time the script ran OR if I've manually logged in to TF2 using Steam. In the latter case, once I exit out and restart the script, the itemSchema becomes available again.

This happens even if I logoff using steam.logOff(), and I'm not sure what else I can do to fully reset the connection without manually entering the game. Any ideas?

Thanks for all your work on this, by the way!

EDIT: Just realized I should probably simply store the item schema, and update it when a new one becomes available.. perhaps this is by design. If so, feel free to close.

**Comment by DoctorMcKay** [comment]
The GC doesn't send the schema on login in my experience. A workaround is to just save it (JSON.stringify) to a file when it's received, and load it on startup.

**Comment by blindinglt** [comment]
Got it, will do. Thanks
