### ISSUE TITLE
writeUInt64LE

### ISSUE THREAD

**Issue by zm3y** [DoctorMcKay/node-tf2#5]
Hello! After @seishun updated node-steam and now it works only with node v0.12. I updated node from 0.10 to 0.12 and see there is no writeUInt64LE in new node. This module (node-tf2) widely uses writeUInt64LE and many functions are not work. Is this node problem or someone must rewrite this module? Thank you for your time and sorry for my english.

**Comment by DoctorMcKay** [comment]
`writeUInt64LE` was never part of node, it's provided by the `ref` module. I guess node 0.12 has some new buffer stuff and node-steam stopped using ref. I don't have time to update this module for node 0.12 just yet, but let me whip up a compatibility branch real quick.

**Comment by DoctorMcKay** [comment]
Okay, remove the npm version and install from `DoctorMcKay/node-tf2#node-0.12-compatibility` and it should work until I can properly update it for 0.12.

**Comment by seishun** [comment]
`ref` should still work on 0.12. I stopped using it because it was the last remaining native dependency and I was indirectly depending on ByteBufer.js anyway.

**Comment by zm3y** [comment]
Im newbie in node and I know is not much. Now work with v0.12. Thank you guys, you do great work. Now I must close this issue or not?

**Comment by DoctorMcKay** [comment]
@seishun Indeed, I just need to remove my own `ref` dependency (I was just inheriting the methods your dependency was adding).

@zm3y No, leave it open as it's still an outstanding issue.

**Comment by DoctorMcKay** [comment]
v1.1.0 is out which should fix this.
